name:                ceditor
version:             0.1.0.0
github:              "lilvadim/ceditor"
license:             BSD3
author:              "Vadim Mostovoy"
maintainer:          "example@example.com"
copyright:           "2021 VM's"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ceditor#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- binary
- bytestring
- directory
- conversion
- sort
- gloss
- gloss-juicy

library:
  source-dirs: src

executables:
  ceditor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ceditor

tests:
  ceditor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ceditor
